#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

if (file_exists($maintenance = __DIR__ . '/storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__ . '/vendor/autoload.php';

$status = (require_once __DIR__ . '/bootstrap/app.php')
    ->handleCommand(new \Symfony\Component\Console\Input\ArgvInput);

exit($status);